del *.~???
del dcu\*.dcu
del bircd.exe
del bircd
del bircd.map
del *.ppu
del *.o
del *.ppw
del *.ow
del bcreationdate.pas
del bcreationdate.exe
del bcreationdate
del mkpasswd
del bcreationdate
del stdout.txt
del bircd.pid
